### ISSUE TITLE
Zeroing out "Y-Axis" Machine Position doesn't seem to work?

### ISSUE THREAD

**Issue by justinlevi** [makermadecnc/makerverse#42]
Here's quick screen recording of me trying to zero out the machine Position Y coordinates after centering the M2 at the middle of my workspace. Noticed that the Position is never zeroed even after clicking the "Zero out Machine" button.

Clicking the "Set Home" button does not zero out the Y Machine position either. 

![zero](https://user-images.githubusercontent.com/1117989/96387857-31d6bd00-1173-11eb-85c5-98c3645464bc.gif)

**Comment by zaneclaes** [comment]
This was fixed in the 1.1.1 beta, about 6 weeks ago.
