### ISSUE TITLE
speed setting during cuts

### ISSUE THREAD

**Issue by makerorne** [makermadecnc/makerverse#58]
i dont know if i am at the right place to talk about this, but is it possible in a next version of makerverse, to have a function to change speed of movements during cut ? (0-120% for example) I have this on my 3d printer (with duetwifi mainboard) and it is usefull when you see that speed is not perfect during cut.
thanks for all the job made on thi soft

**Comment by zaneclaes** [comment]
Sure thing! In fact, it was already recommended, discussed, and planned in another open issue, [here](https://github.com/makermadecnc/makerverse/issues/47). Unfortunately I'm still working on this very major update, so it's still not out yet :(
