### ISSUE TITLE
where is the pause keyword

### ISSUE THREAD

**Issue by montitrasta** [makermadecnc/makerverse#71]
i try to pause the makerverse program with my keyboard but there is no keyword.

**Comment by zaneclaes** [comment]
In most cases (like GRBL based machines), the command for feedhold is ! (exclamation), which may be issued via the terminal (as with any other command). Or see the shortcuts docs from CNCjs: https://cnc.js.org/docs/user-guide/

**Comment by montitrasta** [comment]
thank you
