### ISSUE TITLE
Need manual CNC controls which are spaced out from the Home/Diagonal buttons

### ISSUE THREAD

**Issue by BirdTho** [makermadecnc/makerverse#80]
I have this issue when trying to operate CNC JS in manual mode.
I would probably try and fork it, but I haven't gotten it to work locally because of some i18n errors and whatnot.

But when I was on several occasions trying to move the router in X and Y directions using the UI on my mobile phone, the buttons are small and easy to miss on. I was manually making a little pocket in some material, and accidentally hit the Home(X/Y) button which shredded my workpiece. 

On another occasion I was jogging -X by 3mm per tap while facing my X axis fence (I have a piece of 1/8" aluminum I use as a reference surface for lining up work). Well, I accidentally hit the -X,-Y diagonal button and ate into the aluminum, ruining the spindle on my 3018 CNC.

I need an option to disable these buttons or move them elsewhere on the UI. This is freakin' killing me.

**Comment by zaneclaes** [comment]
> I have this issue when trying to operate CNC JS in manual mode.
This github repository is for Makerverse (not CNCjs).

In any case, it sounds like you're trying to use the app on a mobile/tablet interface. In order to do so, you should be using the Tablet UI, as [described in the documentation](https://makerverse.com/features/widgets/#tablet-ui).
