### ISSUE TITLE
Getting error: certificate has expired, when trying to login to standalone app

### ISSUE THREAD

**Issue by tandlcreations** [makermadecnc/makerverse#81]
Getting the error, "certificate has expired" when trying to login to standalone app on Windows 10 computer.  Have tried installing latest version.  Was hoping to get some work done today...  Any guidance you can provide would be great!

![image](https://user-images.githubusercontent.com/39632372/135641643-6c8c904f-28fd-41b5-ba77-c8e995066b8d.png)

**Comment by zaneclaes** [comment]
tl;dr — the fix went live about 5 minutes ago. Please try again and LMK how it goes.

Full explanation: the problem had to do with Electron, and affected only the desktop (stand-alone) versions of Makerverse. Dozens of different desktop apps around the world are currently dead in the water, beginning on the morning of Sept 30th 2021... as you can read about here: https://github.com/electron/electron/issues/31212

**Comment by zaneclaes** [comment]
We've had two other users verify that things are working again, so I'm going to close this issue for now. Feel free to ping me if needed @jdhoneatt .

**Comment by tandlcreations** [comment]
I can confirm it is working for me too.  Thanks for the quick response!
