### ISSUE TITLE
Makerverse crashing, dropping program file

### ISSUE THREAD

**Issue by RuckusGarage** [makermadecnc/makerverse#91]
Seemingly randomly Makerverse will simply stop; the machine runs for a short time after the software locks up and then the machine stops, the program is lost/removed. The only command that is accepted is pause and then a software restart is required to recover the machine and get everything back to home. This has been an ongoing issue for us for quite some time starting with build 1.1.3 and continuing into the current beta build we've been using, 1.1.5. Today it happened four separate times on two different .NC files at different points in the program. 

Our current SOP has staff restarting the computer and power cycling the Arduino in an effort to minimize crashes and the wasted time running programs multiple times. We've even gone so far as to break cuts into half hour to hour segments so as not to waste so much time when this happens. It goes without saying that this is frustrating and time consuming. 

Does the software log at all? Where would I find those?

Is there a known issue causing this problem and is there a solution? 

Best regards, RG

Makerverse 1.1.5
Maslow Due Ver 1.1g 20200909 
Dell Laptop i3-M350 2.27
4GB RAM 
Windows 10 Home 64 bit
Both laptop and Due are plugged into a UPS

**Comment by RuckusGarage** [comment]
Update; tried running the file again, crashed. Tried running a different file, crashed. Uninstalled and reverted back to 1.1.3 and tried again, crashed.

**Comment by RuckusGarage** [comment]
Update: First cut of the day went fine. Second and third resulted in a new type of failure. The software crashed early on in the program but the program completed 100%. 

Reinstalled 1.1.5 and the fourth cut failed in a short time and in the original way.

**Comment by RuckusGarage** [comment]
Tried an older file that's been cut successfully twice before today with the same result. After 2+ hours of cutting the machine just stops and the software dumped the program. At this point we've eliminated everything as a variable with the exception of the passage of time and the material being cut (different manufacture, same material). 

Are there known issues with the M2 Arduino Due failing? How about static discharge failures?

**Comment by zaneclaes** [comment]
This sounds like a hardware issue. Specifically, this happens when the USB connection is interrupted for some reason. It could be a loose USB connection, bad cable, bad board, etc. Really, anything that would interrupt the connection stream with the machine.

> Does the software log at all? Where would I find those?

Software logs are printed to stdout.
