### ISSUE TITLE
Network Error - Can't Login

### ISSUE THREAD

**Issue by pauljacob95** [makermadecnc/makerverse#95]
![image](https://user-images.githubusercontent.com/99104323/152664004-fc3f9fcd-1965-406a-96a6-e7de3e2192c4.png)

Can't login 
See picture, I've tried three devices across two internet connections in browser and in app. No results. Happy to trouble shoot things if helpful.

**Comment by pauljacob95** [comment]
![image](https://user-images.githubusercontent.com/99104323/152664309-d1304c3d-dc4d-4d62-b97a-008e6a3eabc0.png)

update, attempted updating to latest pre-release

**Comment by pauljacob95** [comment]
![image](https://user-images.githubusercontent.com/99104323/152665425-09d8c80a-332d-43d8-b295-9267627f62ed.png)

**Comment by kaibae19** [comment]
Me too.  This occurred yesterday afternoon Pacific time.  I lost the ability for two computers to authenticate over the course of the day.  Based on the CORS error, it suggests that the openwork.shop server was upgraded or changed as we are now missing expected headers for the openid authentication to work correctly.  The following error is also included in the web console:

`Failed to load https://openwork.shop/.well-known/openid-configuration: Redirect from 'https://openwork.shop/.well-known/openid-configuration' to 'https://www.openwork.shop/.well-known/openid-configuration' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:54720/' is therefore not allowed access.`

As a workaround - setting local GuestAccess mode allows you to connect to the Makerverse instance. https://makerverse.com/features/advanced/

**Comment by skilescm** [comment]
Looking into this now. Thank you for the detailed error logs.

**Comment by rspeed** [comment]
I've had some weird issues with logging in. Though it just brought me back to the login screen without any errors. The workaround I figured out was to go to the Open Workshop home page and clicking on the login button in the upper-right corner. Once I was logged in, returning to the Makerverse login worked correctly.

**Comment by pauljacob95** [comment]
Cheers skilescm working for now, I have since been cutting on the machine without any interruptions. not sure when it came good.

Cheers for the feedback, kaibae and rspeed, 
Hopefully i wont have to try the login trick.

**Comment by pauljacob95** [comment]
hi @kaibae19 I tried this but doesn't seem to work. 
havnt coded before. was wondering if this is the right place to put the boolean key.
![image](https://user-images.githubusercontent.com/99104323/155866085-f0fcec68-1d4f-4526-8d4a-c9f003086409.png)

**Comment by pauljacob95** [comment]
https://makermade.freshdesk.com/support/discussions/topics/44001018377

also tried this but no luck

**Comment by kaibae19** [comment]
@pauljacob95 The directive goes outside the state block:

```
{
    "insecureDangerousGuestAccess": true,
    "verbosity": 3,
    "state": {
        "checkForUpdates": true,
        "prereleases": false,
        "controller": {
            "exception": {
                "ignoreErrors": false
            }
        }
    },
    "secret": "pw"
}
```

Also, you can leave off the verbosity statement, it increase the detail in the logging.  I believe it was defaulted to 1 or simply wasn't defined - fyi.

**Comment by pauljacob95** [comment]
Works! Love you XoX

**Comment by skilescm** [comment]
Can you check the console and see if it is a CORS error?
